#!/usr/bin/env python3
"""
VAX binary encoder — canonical encoder for SIMH JIT tests.

Encodes a fixed set of VAX instructions sufficient to test the
basic calling-convention smoke tests without needing a cross-assembler.

VAX operand specifier reference:
  0x00–0x3F  Short literal (value = specifier & 0x3F)
  0x4n       Index (register n)
  0x5n       Register Rn
  0x6n       Register deferred (Rn)
  0x7n       Autodecrement -(Rn)
  0x8n       Autoincrement (Rn)+  ; 0x8F = PC → immediate (4-byte)
  0x9n       Autoincrement deferred  ; 0x9F = absolute address (4-byte)
  0xAn       Byte displacement(Rn)  + 1-byte disp
  ...
  0xCn       Word displacement(Rn)  + 2-byte disp
  0xEn       Longword displacement(Rn) + 4-byte disp

Register numbers: R0=0 … R11=11, AP=12, FP=13, SP=14, PC=15
"""

import struct

R0, R1, R2, R3, R4, R5, R6, R7 = range(8)
R8, R9, R10, R11 = range(8, 12)
AP, FP, SP, PC = 12, 13, 14, 15


# ── Addressing modes ──────────────────────────────────────────────────────────

def reg(r):
    """Register direct operand specifier."""
    return bytes([0x50 | r])


def imm_long(val):
    """Immediate longword operand: mode=8 reg=PC (0x8F) + 4-byte LE value."""
    return bytes([0x8F]) + struct.pack('<i', val)


def short_lit(val):
    """Short literal (0..63): single byte."""
    assert 0 <= val <= 63
    return bytes([val & 0x3F])


def abs_addr(addr):
    """Absolute address operand: mode=9 reg=PC (0x9F) + 4-byte LE address."""
    return bytes([0x9F]) + struct.pack('<I', addr)


def pc_rel_byte(disp):
    """PC-relative byte displacement operand: mode=A reg=PC (0xAF) + 1-byte LE disp."""
    return bytes([0xAF]) + struct.pack('<b', disp)


def w_disp_pc(disp16):
    """Word displacement relative to PC (W^ in VAX asm).

    Encodes as: 0xCF followed by signed 16-bit displacement.
    The displacement is relative to the byte immediately after the
    2-byte displacement field (i.e. caller pre-computes target - pc_after_operand).
    """
    return bytes([0xCF]) + struct.pack('<h', disp16)


# ── Instructions ──────────────────────────────────────────────────────────────

def HALT():
    return bytes([0x00])

def NOP():
    return bytes([0x01])

def RET():
    return bytes([0x04])

def BRW(disp16):
    """BRW: unconditional branch, 16-bit signed displacement (from end of instr)."""
    return bytes([0x31]) + struct.pack('<h', disp16)

def BRB(disp8):
    """BRB: unconditional byte branch, 8-bit signed displacement (from end of instr)."""
    return bytes([0x11, disp8 & 0xFF])

def BGTR(disp8):
    """BGTR: branch if greater (signed), 8-bit displacement."""
    return bytes([0x14, disp8 & 0xFF])

def BLEQ(disp8):
    """BLEQ: branch if less or equal (signed), 8-bit displacement."""
    return bytes([0x15, disp8 & 0xFF])

def BNEQ(disp8):
    """BNEQ: branch if not equal, 8-bit displacement."""
    return bytes([0x12, disp8 & 0xFF])

def BEQL(disp8):
    """BEQL: branch if equal, 8-bit displacement."""
    return bytes([0x13, disp8 & 0xFF])

def BGEQ(disp8):
    """BGEQ: branch if greater or equal (signed), 8-bit displacement."""
    return bytes([0x18, disp8 & 0xFF])

def BLSS(disp8):
    """BLSS: branch if less (signed), 8-bit displacement."""
    return bytes([0x19, disp8 & 0xFF])

def MOVL(src_spec, dst_spec):
    return bytes([0xD0]) + src_spec + dst_spec

def CLRL(dst_spec):
    return bytes([0xD4]) + dst_spec

def ADDL2(src, dst):
    """ADDL2: add src to dst, result in dst."""
    return bytes([0xC0]) + src + dst

def ADDL3(src1, src2, dst):
    return bytes([0xC1]) + src1 + src2 + dst

def SUBL2(src, dst):
    """SUBL2: subtract src from dst, result in dst."""
    return bytes([0xC2]) + src + dst

def INCL(dst):
    """INCL: increment longword."""
    return bytes([0xD6]) + dst

def DECL(dst):
    """DECL: decrement longword."""
    return bytes([0xD7]) + dst

def TSTL(src):
    """TSTL: test longword (set condition codes)."""
    return bytes([0xD5]) + src

def CALLS(count_spec, dst_spec):
    """CALLS count, destination."""
    return bytes([0xFB]) + count_spec + dst_spec

def entry_mask(mask=0):
    """2-byte entry mask at function entry point."""
    return struct.pack('<H', mask)

def PUSHL(src_spec):
    """PUSHL — push longword onto stack."""
    return bytes([0xDD]) + src_spec


# ── .ini generation helpers ───────────────────────────────────────────────────

def ini_header(name, generator):
    """Return lines for the top of a generated .ini file."""
    return [
        f'; {name}',
        f'; AUTO-GENERATED by {generator} — do not edit by hand',
        f'; Re-generate: python3 VAX/tests/jit/{generator} > VAX/tests/jit/{name}.ini',
        '',
    ]

def deposit_bytes(blob, base_addr=0):
    """Return deposit -b lines for a byte sequence."""
    lines = []
    for i, b in enumerate(blob):
        lines.append(f'deposit -b {base_addr + i:x} {b:02x}')
    return lines

def ini_setup(regs_to_zero=None, pc=0, sp=None):
    """Return deposit lines to initialize registers."""
    lines = []
    regs = regs_to_zero if regs_to_zero is not None else list(range(14))  # R0-R13
    for r in regs:
        lines.append(f'deposit r{r} 0')
    lines.append(f'deposit pc {pc:x}')
    if sp is not None:
        lines.append(f'deposit r14 {sp:x}')
    return lines

def ini_run_examine(breakpoint_addr, regs_to_examine=None):
    """Return set break, go, and examine lines."""
    regs = regs_to_examine or [
        'r0','r1','r2','r3','r4','r5','r6','r7',
        'r8','r9','r10','r11','r12','r13','r14','psl',
    ]
    lines = [f'set break {breakpoint_addr:x}', 'go']
    for r in regs:
        lines.append(f'examine {r}')
    return lines


# ── Test programs (kept from reference encode_vax.py) ────────────────────────

def build_test_ret42(base_harness=0x4000, base_func=0x4200):
    """
    Harness at base_harness:
        calls #0, func      ; call function
        halt                ; stop

    Function at base_func:
        .word 0             ; entry mask
        movl $42, r0        ; return value
        ret
    """
    harness = (
        CALLS(short_lit(0), abs_addr(base_func)) +
        HALT()
    )
    func = (
        entry_mask(0) +
        MOVL(imm_long(42), reg(R0)) +
        RET()
    )
    return harness, func


def build_test_add(base_harness=0x4000, base_func=0x4200):
    """
    Harness:
        pushl $7            ; arg 2
        pushl $5            ; arg 1
        calls #2, func
        halt

    Function (add two args):  -- requires arg passing (Phase 8)
        -- Not yet: just placeholder returning 12 hard-coded
        .word 0
        movl $12, r0
        ret
    """
    harness = (
        PUSHL(imm_long(7)) +
        PUSHL(imm_long(5)) +
        CALLS(short_lit(2), abs_addr(base_func)) +
        HALT()
    )
    func = (
        entry_mask(0) +
        MOVL(imm_long(12), reg(R0)) +
        RET()
    )
    return harness, func


def generate_simh_script(tests, sp=0x8000):
    """
    Generate a SIMH command script that:
      1. Deposits each test's bytes at its addresses
      2. Sets SP and PC
      3. Runs to HALT
      4. Examines R0
    """
    lines = [
        '; VAX SIMH smoke test — auto-generated',
        '; MicroVAX 3900',
        '',
    ]

    for name, (harness, harness_addr, func, func_addr) in tests.items():
        lines.append(f'; === Test: {name} ===')
        for i, b in enumerate(harness):
            lines.append(f'deposit -b {harness_addr + i:x} {b:x}')
        for i, b in enumerate(func):
            lines.append(f'deposit -b {func_addr + i:x} {b:x}')
        lines.append(f'deposit pc {harness_addr:x}')
        lines.append(f'deposit sp {sp:x}')
        lines.append(f'run')
        lines.append(f'examine r0')
        lines.append('')

    lines.append('quit')
    return '\n'.join(lines)


if __name__ == '__main__':
    harness42, func42 = build_test_ret42(0x4000, 0x4200)
    harness_add, func_add = build_test_add(0x4100, 0x4300)

    tests = {
        'ret42': (harness42, 0x4000, func42, 0x4200),
    }

    script = generate_simh_script(tests)
    print(script)

    import sys
    print('\n; --- Byte sequences ---', file=sys.stderr)
    print(f'; harness42: {harness42.hex(" ")}', file=sys.stderr)
    print(f'; func42:    {func42.hex(" ")}', file=sys.stderr)
